In [1]:
import numpy as np
import math

In [2]:
# S&P data for five years, 2013-2017
sp = np.array([1692, 1978, 1884, 2151, 2519])
# ABC corporation
abc = np.array([68, 102, 110, 112, 154])

In [24]:
# Compute returns

def rates(time_series):
    deltas = np.diff(time_series)
    rates = deltas/time_series[1:]
    return rates

def mean_rate(times_series):
    return np.mean(rates(times_series))

print(rates(sp))
print(mean_rate(sp))

[ 0.1445905  -0.04989384  0.12412831  0.14608972]
0.09122867077935679


In [25]:
rates_of_return = [mean_rate(sp), mean_rate(abc)]
rates_of_return

[0.09122867077935679, 0.17416125541125538]

In [31]:
# Portfolio return

def portfolio_return(weights):
  return np.dot(weights, rates_of_return)

w1 = np.array([1.0, 0.0])
w2 = np.array([0.5, 0.5])
w3 = np.array([0.0, 1.0])

print(1, portfolio_return(w1))
print(2, portfolio_return(w2))
print(3, portfolio_return(w3))

1 0.09122867077935679
2 0.1326949630953061
3 0.17416125541125538


In [28]:
# Compute risks

def risk(time_series):
    mean_ = np.mean(time_series)
    var_  = np.var(time_series)
    risk_ = math.sqrt(var_)/mean_
    return risk_

risk(sp), risk(abc)

(0.1367458343689953, 0.25128311921087904)

In [32]:
# Wrong way to compute portfolio risks

risks = [risk(sp), risk(abc)]

def portfolio_risk_bad(weights):
    return np.dot(weights, risks)

print(1, portfolio_risk_bad(w1))
print(2, portfolio_risk_bad(w2))
print(3, portfolio_risk_bad(w3))

1 0.1367458343689953
2 0.19401447678993716
3 0.25128311921087904


In [26]:
# Compute covariance

sp_mean = np.mean(sp)
sp_var = np.var(sp)
sp_mean, sp_var, round(math.sqrt(sp_var),2), round(math.sqrt(sp_var)/sp_mean,2)

(2044.8, 78186.16, 279.62, 0.14)

0.14

In [5]:
abc_mean = np.mean(abc)
abc_var = np.var(abc)
abc_mean, abc_var, round(math.sqrt(abc_var),2), round(math.sqrt(abc_var)/abc_mean,2)

(109.2, 752.96, 27.44, 0.25)

In [6]:
def normalize(time_series):
    return time_series - np.mean(time_series)

normalize(sp), normalize(abc)

(array([-352.8,  -66.8, -160.8,  106.2,  474.2]),
 array([-41.2,  -7.2,   0.8,   2.8,  44.8]))

In [7]:
def cov2(ts1, ts2):
    nts1 = normalize(ts1)
    nts2 = normalize(ts2)
    n = len(nts1)
    cov_ = np.sum(nts1*nts2)/n
    return round(cov_, 2)
    
c = cov2(sp, abc)
c

7285.84

In [35]:
def covariance(ts1, ts2):
    s11 = np.var(ts1)
    s22 = np.var(ts2)
    s12 = cov2(ts1,ts2)
    return np.array([[s11, s12], [s12, s22]])
    
cm = covariance(sp, abc)
cm

array([[78186.16,  7285.84],
       [ 7285.84,   752.96]])

In [36]:
np.linalg.det(cm)

5787586.528000001

In [37]:
np.trace(cm)

78939.12000000001

In [38]:
def portfolio_variance(weights, cov):
    return np.dot(weights, np.dot(cov, weights))

def portfolio_risk(weights, cov):
    c = portfolio_variance(weights, cov)
    r = math.sqrt(c)
    return round(r,2)

def portfolio_mean(weights):
    means = [sp_mean, abc_mean]
    return np.dot(weights, means)

def portfolio_rel_risk(weights, cov):
    c = portfolio_variance(weights, cov)
    r = math.sqrt(c)/portfolio_mean(weights)
    return round(r,4)


In [39]:
print(1, portfolio_variance(w1, cm), portfolio_risk(w1, cm), portfolio_rel_risk(w1, cm))
print(2, portfolio_variance(w2, cm), portfolio_risk(w2, cm), portfolio_rel_risk(w2, cm))
print(3, portfolio_variance(w3, cm), portfolio_risk(w3, cm), portfolio_rel_risk(w3, cm))

1 78186.16 279.62 0.1367
2 23377.7 152.9 0.142
3 752.96 27.44 0.2513
