In [1]:
# PageRank references: 
#   http://blog.kleinproject.org/?p=280

# States: Sunny, Cloudy, Rainy

from numpy.random import choice
import numpy as np

states = ['S', 'C', 'R']
def nextState(state):
    if state == 'S':
        return choice(states, p=[0.8, 0.15, 0.05])
    elif state == 'C':
        return choice(states, p=[0.2, 0.5, 0.3])
    else:
        return choice(states, p=[0.2, 0.2, 0.6])
        

In [2]:
nextState('S'), nextState(_), nextState(_),nextState(_),nextState(_)

('S', 'C', 'S', 'C', 'R')

In [3]:
def run_as_string(initial_state, n):
    output = initial_state
    for i in range(0, n):
        s = nextState(output[-1])
        output = output + s
    return output 

In [4]:
run_as_string('S', 20)

'SSSSSSSSSSSCCCCSSSSSS'

In [5]:
def run(initial_state, n):
    output = [initial_state]
    for i in range(0, n):
        s = nextState(output[-1])
        output.append(s)
    return output

print(run('S', 20))
    

['S', 'S', 'S', 'C', 'C', 'C', 'S', 'S', 'S', 'C', 'C', 'C', 'C', 'S', 'S', 'R', 'R', 'R', 'R', 'C', 'R']


In [6]:
def counts(input):
    output = [0,0,0]
    for state in input:
        if state == 'S':
            output[0] = output[0] + 1
        elif state == 'C':
            output[1] = output[1] + 1
        else:
            output[2] = output[2] + 1
    return np.array(output)

In [7]:
counts(run('S',1000))

array([508, 252, 241])

In [8]:
counts(run_as_string('S',1000))

array([437, 277, 287])

In [9]:
def frequencies(input):
    return counts(input)/len(input)

In [10]:
f1 = frequencies(run('S', 100)); f2 = frequencies(run('S', 100))
f1, f2 , np.abs(f1 - f2)

(array([0.5049505 , 0.22772277, 0.26732673]),
 array([0.54455446, 0.18811881, 0.26732673]),
 array([0.03960396, 0.03960396, 0.        ]))

In [11]:
f1 = frequencies(run('S', 1000)); f2 = frequencies(run('S', 1000))
f1, f2, np.abs(f1 - f2)

(array([0.51148851, 0.26973027, 0.21878122]),
 array([0.47852148, 0.24175824, 0.27972028]),
 array([0.03296703, 0.02797203, 0.06093906]))

In [12]:
f1 = frequencies(run('S', 10000)); f2 =  frequencies(run('S', 10000))
f1, f2, np.abs(f1 - f2)

(array([0.48365163, 0.25227477, 0.26407359]),
 array([0.48485151, 0.25387461, 0.26127387]),
 array([0.00119988, 0.00159984, 0.00279972]))

In [13]:
f1 = frequencies(run('S', 100000)); f2 = frequencies(run('S', 100000))
f1, f2, np.abs(f1 - f2)

(array([0.49739503, 0.25085749, 0.25174748]),
 array([0.50298497, 0.24733753, 0.2496775 ]),
 array([0.00558994, 0.00351996, 0.00206998]))

In [14]:
# The secret revealed!

M = np.array([[0.8, 0.2, 0.2], [0.15, 0.5, 0.2], [0.05, 0.3, 0.6]])
M

array([[0.8 , 0.2 , 0.2 ],
       [0.15, 0.5 , 0.2 ],
       [0.05, 0.3 , 0.6 ]])

In [15]:
def iterate(A,v,n):
    for i in range(0,n):
        v = np.dot(A,v)
    return v

s = np.array([1,0,0])

In [16]:
iterate(M, s, 3)

array([0.608 , 0.2275, 0.1645])

In [17]:
iterate(M, s, 4)

array([0.5648 , 0.23785, 0.19735])

In [18]:
iterate(M, s, 10)

array([0.50302331, 0.24949513, 0.24748156])

In [19]:
iterate(M, s, 100)

array([0.5 , 0.25, 0.25])

In [20]:
def experiment(start, n):
    result = frequencies(run(start,n))
    result = map(lambda x: round(x,3), result)
    return list(result)

In [21]:
def run_experiments(n):
    for i in range(2,n):
        print(10**i, experiment('S',10**i))

In [22]:
run_experiments(6)

100 [0.505, 0.307, 0.188]
1000 [0.464, 0.249, 0.288]
10000 [0.51, 0.238, 0.252]
100000 [0.499, 0.246, 0.255]


In [23]:
experiment('S',100)

[0.505, 0.228, 0.267]

In [24]:
from math import log
log(5) - 2*(log(20) + log(3.1416)) + 50*log(5)

73.80040453846782

In [25]:
np.e**73.80040453846782

1.12488584866895e+32

In [26]:
k = -49*(1/2)*(log(40) + log(3.1416)) + 1000*log(50)

In [27]:
k - log(10)

3791.2969342144597

In [28]:
log(10)

2.302585092994046

In [29]:
pp = np.array([0.5, 0.25, 0.25])

In [31]:
np.dot(pp, M.T)

array([0.5 , 0.25, 0.25])

In [32]:
M.T

array([[0.8 , 0.15, 0.05],
       [0.2 , 0.5 , 0.3 ],
       [0.2 , 0.2 , 0.6 ]])

In [45]:
c = M[2,:]
c

array([0.05, 0.3 , 0.6 ])

In [46]:
np.dot(c,pp)

0.25