# Eigenvectors and the power method


In [1]:
# Lets import numpy and then get familiar with some numpy operations
import numpy as np


In [2]:
a = np.array([3,-1,-1,2])
b = np.array([1,2,3,4])

In [3]:
# ADD:  
a + b

array([4, 1, 2, 6])

In [4]:
# SUBTRACT
a - b

array([ 2, -3, -4, -2])

In [5]:
# SCALAR MULTIPLICATION
2*b

array([2, 4, 6, 8])

In [6]:
# LINEAR COMBINATION
2*a + 3*b

array([ 9,  4,  7, 16])

In [7]:
# COMPONENTWISE PRODUCT
a*b

array([ 3, -2, -3,  8])

In [8]:
# DOT PRODUCT
np.dot(a,b)
a

array([ 3, -1, -1,  2])

In [9]:
# MAKE A MATRIX
A = a.reshape(2,2)
A

array([[ 3, -1],
       [-1,  2]])

In [10]:
# ANOTHER ONE
B = b.reshape(2,2)
B

array([[1, 2],
       [3, 4]])

In [11]:
# MULTIPLY THEM
A*B

array([[ 3, -2],
       [-3,  8]])

In [12]:
# HMMM .. THAT WAS COMPONENTWISE MULTIPLICATION
# ANOTHER WAY
np.dot(A,B)

array([[0, 2],
       [5, 6]])

In [13]:
# THAT WAS MATRIX MULTPILCATION
# A LITTLE GAME, PART 1
v = np.array([1,0])
print(A)
np.dot(A,v)

[[ 3 -1]
 [-1  2]]


array([ 3, -1])

In [14]:
np.dot(v,A)

array([ 3, -1])

In [15]:
w = v;
for i in range(0,10):
    w = np.dot(A,w)
    w = (1/w[0])*w
w

array([ 1.        , -0.61797753])

In [16]:
ww = np.dot(A,w)
ww

array([ 3.61797753, -2.23595506])

In [17]:
ww/w

array([3.61797753, 3.61818182])

## Construct a big matrix

In [18]:
# Your problem: find the domininant eigenvalue 
# and eigenvector of the matrix C below

In [19]:
C = np.fromfunction(lambda i, j: 1/(1 + i + j), (5, 5), dtype=float)
C

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [20]:
w = np.array([1,1,1,1,1]);
for i in range(0,10):
    w = np.dot(C,w)
    w = (1/w[0])*w
w

array([1.        , 0.58056692, 0.41880095, 0.33006105, 0.27325824])

In [21]:
ww = np.dot(C,w)

In [22]:
ww/w

array([1.56705069, 1.56705069, 1.56705069, 1.56705069, 1.56705069])